# Rooted foliage.
block.10000 = short_grass tall_grass short_dry_grass tall_dry_grass fern
# Free foliage (leaves).
block.10001 = oak_leaves spruce_leaves jungle_leaves birch_leaves cherry_leaves pale_oak_leaves mangrove_leaves dark_oak_leaves acacia_leaves azalea_leaves flowering_azalea_leaves vine

# Water.
block.10002 = water flowing_water

# IDs starting from 11000 are used for mass detection, e.g., for determining if a fragment should have SSR

block.11000 = iron_block
block.11001 = gold_block
block.11002 = diamond_block
block.11003 = emerald_block
block.11004 = netherite_block
block.11005 = obsidian
