iris.features.optional = TEXTURE_FILTERING

screen = <profile> [Atmosphere] [Lighting] [Materials] [Water] [Debug] [Post_Processing] 

# Main submenus.
screen.Atmosphere = [FOG] 
screen.Lighting = [Shadows] [Sky]
screen.Water = WATER_WAVE_AMPLITUDE
screen.Materials = [POM] WAVING_FOLIAGE NORMAL_MAPPING SPECULAR_MAPPING
screen.Debug = DEBUG_VIEW DEBUG_BUFFER
screen.Post_Processing = [SSAO] [Denoising] [Bloom]
# Submenus.
# Lighting.
screen.FOG = FOG FOG_DENSITY 
screen.Shadows = SHADOWS SHADOW_MAP_RESOLUTION SHADOW_BIAS SHADOW_RANGE SHADOW_RADIUS
screen.Sky = [Blocklight] [Skylight] SUNLIGHT_COLOR_INTENSITY AMBIENT_COLOR_INTENSITY
screen.Blocklight = BLOCKLIGHT_COLOR_R BLOCKLIGHT_COLOR_G BLOCKLIGHT_COLOR_B
screen.Skylight = [Sky_Colors] <empty> <empty> SKYLIGHT_COLOR_R SKYLIGHT_COLOR_G SKYLIGHT_COLOR_B 
# Materials.
screen.POM = POM POM_HEIGHT_SCALE POM_MIN_LAYERS POM_MAX_LAYERS
# Post processing.
screen.SSAO = SSAO SSAO_SAMPLE_COUNT SSAO_RADIUS SSAO_BIAS
screen.Denoising = SMART_DENOISING SIGMA K_SIGMA THRESHOLD
screen.Bloom = BLOOM BLOOM_RADIUS

# Sliders.
sliders = FOG_DENSITY SHADOW_MAP_RESOLUTION NOISE_TEXTURE_RESOLUTION SHADOW_BIAS SUNLIGHT_COLOR_INTENSITY AMBIENT_COLOR_INTENSITY WATER_WAVE_AMPLITUDE SSAO_SAMPLE_COUNT SSAO_RADIUS SSAO_BIAS POM_HEIGHT_SCALE POM_MIN_LAYERS POM_MAX_LAYERS SHADOW_RANGE SHADOW_RADIUS SIGMA K_SIGMA THRESHOLD BLOOM_RADIUS DEBUG_BUFFER

# Customization.
screen.Sky_Colors.columns = 3
screen.Blocklight.columns = 3
screen.Skylight.columns = 3

# Option disables.
#if SHADOWS == 0
shadow.enabled = false
#endif
#if BLOOM == 0
program.world0/composite4.enabled = false
program.world0/composite5.enabled = false
#endif
#if SSAO == 0
program.world0/composite.enabled = false
program.world0/composite1.enabled = false
#endif
#if FOG == 0
program.world0/composite3.enabled = false
#endif
#if SMART_DENOISING == 0
program.world0/composite98.enabled = false
#endif

# Replace white noise with blue noise.
texture.noise = textures/blue_noise_256.png
