iris.features.optional = TEXTURE_FILTERING

screen = <profile> [Atmosphere] [Lighting] [Materials/PBR] [Water] [Debug] [Post_Processing] 


# Main submenus.
screen.Atmosphere = [Fog] [Sun/Moon] [Sky]
screen.Lighting = [Direct_Lighting] [Indirect_Lighting] [Shadows] 
screen.Water = WATER_WAVE_AMPLITUDE
screen.Materials/PBR = [POM] [Emissions] [SSS] [Waving] 
screen.Debug = DEBUG_VIEW DEBUG_BUFFER DEBUG_COVER_SCREEN
screen.Post_Processing = [Denoising] [Bloom] [SSR]


# Submenus.
screen.Fog = FOG FOG_DENSITY 
screen.Sun/Moon = SUN_MOON_SIZE_SCALAR SUN_MOON_AXIS_ROTATION
screen.Sky = PBR_SKY LIGHT_INTENSITY <empty> <empty> <empty> <empty> S_R S_M S_S RAYLEIGH_SCATTER_R RAYLEIGH_SCATTER_G RAYLEIGH_SCATTER_B

screen.Direct_Lighting = [Blocklight] [Skylight] [Sunlight]
screen.Sunlight = SUNLIGHT_INTENSITY MOONLIGHT_INTENSITY
screen.Blocklight = <empty> BLOCKLIGHT_INTENSITY_MULTIPLIER <empty> BLOCKLIGHT_R BLOCKLIGHT_G BLOCKLIGHT_B
screen.Skylight = <empty> SKYLIGHT_INTENSITY_MULTIPLIER <empty>

screen.Indirect_Lighting = AMBIENT_OCCLUSION AMBIENT_INTENSITY <empty> <empty> SSAO_SAMPLE_COUNT SSAO_RADIUS SSAO_BIAS SSAO_BLUR_RADIUS <empty> <empty> VANILLA_AO

screen.Shadows = [RSM] SHADOWS SHADOW_MAP_RESOLUTION SHADOW_BIAS SHADOW_RANGE PCF_SHADOW_RADIUS
screen.RSM = RSM RSM_SAMPLE_COUNT RSM_SAMPLE_RADIUS RSM_BRIGHTNESS


# Materials.
screen.POM = POM POM_HEIGHT_SCALE POM_LAYERS POM_DEPTH_WRITE
screen.Emissions = EMISSION_STRENGTH
screen.SSS = SSS SSS_SAMPLE_COUNT SSS_STRENGTH OPTICAL_DENSITY_MULTIPLIER
screen.Waving = WAVING_FOLIAGE WAVING_WATER


# Post processing.
screen.Denoising = SMART_DENOISING SIGMA K_SIGMA THRESHOLD
screen.Bloom = BLOOM BLOOM_RADIUS 
screen.SSR = SSR SSR_VISIBILITY SSR_STEPS SSR_QUALITY SSR_ENERGY_THRESHOLD


# Sliders.
sliders = FOG_DENSITY SHADOW_MAP_RESOLUTION NOISE_TEXTURE_RESOLUTION SHADOW_BIAS BLOCKLIGHT_INTENSITY_MULTIPLIER SKYLIGHT_INTENSITY_MULTIPLIER SUNLIGHT_INTENSITY MOONLIGHT_INTENSITY AMBIENT_INTENSITY WATER_WAVE_AMPLITUDE SSAO_SAMPLE_COUNT SSAO_RADIUS SSAO_BIAS POM_HEIGHT_SCALE POM_LAYERS SHADOW_RANGE PCF_SHADOW_RADIUS SIGMA K_SIGMA THRESHOLD BLOOM_RADIUS BLOOM_INTENSITY DEBUG_BUFFER BLOCKLIGHT_R BLOCKLIGHT_G BLOCKLIGHT_B EMISSION_STRENGTH SSAO_BLUR_RADIUS SUN_MOON_SIZE_SCALAR SUN_MOON_AXIS_ROTATION RSM_SAMPLE_COUNT RSM_SAMPLE_RADIUS RSM_BRIGHTNESS SSS_SAMPLE_COUNT SSS_STRENGTH OPTICAL_DENSITY_MULTIPLIER VANILLA_AO SSR_STEPS SSR_VISIBILITY SSR_QUALITY SSR_ENERGY_THRESHOLD LIGHT_INTENSITY S_R S_M S_S  RAYLEIGH_SCATTER_R RAYLEIGH_SCATTER_G RAYLEIGH_SCATTER_B

# Customization.
screen.Sky.columns = 3
screen.Sky_Colors.columns = 3
screen.Blocklight.columns = 3
screen.Skylight.columns = 3

# Option disables.
#if SHADOWS == 0
shadow.enabled = false
#endif
#if RSM == 0
program.world0/deferred2.enabled = false
program.world0/deferred3.enabled = false
#endif
#if BLOOM == 0
program.world0/composite4.enabled = false
program.world0/composite5.enabled = false
program.world0/composite6.enabled = false
program.world0/composite7.enabled = false
program.world0/composite8.enabled = false
program.world0/composite9.enabled = false
program.world0/composite10.enabled = false
program.world0/composite11.enabled = false
program.world0/composite12.enabled = false
program.world0/composite13.enabled = false
program.world0/composite14.enabled = false
program.world0/composite15.enabled = false
#endif
#if AMBIENT_OCCLUSION == 0
program.world0/deferred.enabled = false
program.world0/deferred1.enabled = false
#endif
#if FOG == 0
program.world0/composite3.enabled = false
#endif
#if SSR == 0
program.world0/composite2.enabled = false
#endif
#if SMART_DENOISING == 0
program.world0/composite98.enabled = false
#endif

# Replace white noise with blue noise.
texture.noise = textures/blue_noise_256.png

# Default options.
# shadow.culling = reversed

# Custom uniforms
uniform.vec2.windowDimensions = vec2(viewWidth, viewHeight)
uniform.vec2.playerTexelSize = 1.0 / windowDimensions
uniform.vec2.shadowTexelSize = 1.0 / shadowMapResolution
uniform.vec3.worldLightVector= 0.01 * vec3(shadowLightPosition)
uniform.float.dayProgress = sunAngle

# Custom buffer sizes.
# size.buffer.colortex2 = 0.5 0.5
# size.buffer.colortex2 = 0.25 0.25
