# ---------------------
#     Settings menu    
# ---------------------

screen = <profile> [Atmosphere] [Lighting] [Materials] [Debug] [Post_Processing] 

# Customization.
screen.Sky.columns = 3
screen.Sky_Colors.columns = 3
screen.Blocklight.columns = 3
screen.Skylight.columns = 3
screen.Indirect_Lighting.columns = 3

# Main submenus.
screen.Atmosphere = [Fog] [Sun/Moon] [Sky]
screen.Lighting = [Direct_Lighting] [Indirect_Lighting] [Shadows] 
screen.Materials = [POM] [Emissions] [SSS] [Waving] 
screen.Debug = DEBUG_VIEW DEBUG_BUFFER DEBUG_COVER_SCREEN WHITEWORLD
screen.Post_Processing = [Denoising] [Bloom] [SSR]

# Submenus.
screen.Fog = FOG FOG_DENSITY 
screen.Sun/Moon = SUN_MOON_SIZE_SCALAR SUN_MOON_AXIS_ROTATION
screen.Sky = PBR_SKY LIGHT_INTENSITY <empty> <empty> <empty> <empty> S_R S_M S_S RAYLEIGH_SCATTER_R RAYLEIGH_SCATTER_G RAYLEIGH_SCATTER_B

screen.Direct_Lighting = [Blocklight] [Skylight] [Sunlight]
screen.Sunlight = SUNLIGHT_INTENSITY MOONLIGHT_INTENSITY
screen.Blocklight = <empty> BLOCKLIGHT_INTENSITY <empty> BLOCKLIGHT_R BLOCKLIGHT_G BLOCKLIGHT_B
screen.Skylight = <empty> SKYLIGHT_INTENSITY <empty>

screen.Indirect_Lighting = AMBIENT_OCCLUSION AO_STRENGTH <empty> SSAO_SAMPLES SSAO_RADIUS SSAO_BLUR_RADIUS <empty> <empty> VANILLA_AO

screen.Shadows = [RSM] SHADOWS SHADOW_MAP_RESOLUTION CONTACT_SHADOWS
screen.RSM = RSM RSM_SAMPLES RSM_RADIUS RSM_BRIGHTNESS

# Materials.
screen.POM = POM POM_HEIGHT_SCALE POM_LAYERS POM_DEPTH_WRITE
screen.Emissions = EMISSION_STRENGTH
screen.SSS = SSS SSS_SAMPLES SSS_STRENGTH OPTICAL_DENSITY_MULTIPLIER
screen.Waving = [Foliage] [Water]

screen.Water = WAVING_WATER WATER_WAVE_AMPLITUDE
screen.Foliage = WAVING_FOLIAGE FOLIAGE_WAVE_AMPLITUDE FOLIAGE_WAVE_SPEED

# Post processing.
screen.Denoising = SMART_DENOISING SIGMA K_SIGMA THRESHOLD
screen.Bloom = BLOOM BLOOM_RADIUS BLOOM_STRENGTH
screen.SSR = SSR SSR_VISIBILITY SSR_STEPS SSR_QUALITY SSR_ENERGY_THRESHOLD

# Sliders.
sliders = FOG_DENSITY SHADOW_MAP_RESOLUTION NOISE_TEXTURE_RESOLUTION BLOCKLIGHT_INTENSITY SKYLIGHT_INTENSITY SUNLIGHT_INTENSITY MOONLIGHT_INTENSITY WATER_WAVE_AMPLITUDE SSAO_SAMPLES AO_STRENGTH SSAO_RADIUS POM_HEIGHT_SCALE POM_LAYERS SIGMA K_SIGMA THRESHOLD BLOOM_RADIUS BLOOM_STRENGTH DEBUG_BUFFER BLOCKLIGHT_R BLOCKLIGHT_G BLOCKLIGHT_B EMISSION_STRENGTH SSAO_BLUR_RADIUS SUN_MOON_SIZE_SCALAR SUN_MOON_AXIS_ROTATION RSM_SAMPLES RSM_SAMPLE_RADIUS RSM_BRIGHTNESS SSS_SAMPLES SSS_STRENGTH OPTICAL_DENSITY_MULTIPLIER VANILLA_AO SSR_STEPS SSR_VISIBILITY SSR_QUALITY SSR_ENERGY_THRESHOLD LIGHT_INTENSITY S_R S_M S_S  RAYLEIGH_SCATTER_R RAYLEIGH_SCATTER_G RAYLEIGH_SCATTER_B FOLIAGE_WAVE_AMPLITUDE FOLIAGE_WAVE_SPEED

# -----------------------
#     Option disables    
# -----------------------
 
# program.world0/deferred3.enabled = false

#if SHADOWS == 0
shadow.enabled = false
#endif
#if RSM == 0
program.world0/deferred2.enabled = false
program.world0/deferred3.enabled = false
#endif
#if BLOOM == 0
program.world0/composite70.enabled = false
program.world0/composite71.enabled = false
program.world0/composite72.enabled = false
program.world0/composite73.enabled = false
program.world0/composite74.enabled = false
program.world0/composite75.enabled = false
program.world0/composite76.enabled = false
program.world0/composite77.enabled = false
program.world0/composite78.enabled = false
#endif
#if AMBIENT_OCCLUSION == 0
program.world0/deferred.enabled = false
program.world0/deferred1.enabled = false
#endif
#if FOG == 0
program.world0/composite3.enabled = false
#endif
#if SSR == 0
program.world0/composite2.enabled = false
#endif
#if SMART_DENOISING == 0
program.world0/composite98.enabled = false
#endif

# ----------------
#     Textures    
# ----------------

texture.noise = textures/blue_noise_256.png
texture.composite.colortex29 = textures/luts/FLog2C_to_WDR-709_65grid_V.1.10.cube-s64.png

# ------------------------------
#     Custom uniforms/buffers    
# ------------------------------

uniform.vec2.windowDimensions = vec2(viewWidth, viewHeight)
uniform.vec3.worldLightVector= 0.01 * shadowLightPosition
uniform.float.dayProgress = sunAngle

# --- PHOTON UNIFORMS FOR WORLD SPACE LIGHT DIR ---

variable.float.view_up_dir_norm = 1.0 / sqrt((upPosition.x * upPosition.x) + (upPosition.y * upPosition.y) + (upPosition.z * upPosition.z))
variable.float.view_up_dir_x = upPosition.x * view_up_dir_norm
variable.float.view_up_dir_y = upPosition.y * view_up_dir_norm
variable.float.view_up_dir_z = upPosition.z * view_up_dir_norm
uniform.vec3.view_up_dir = vec3(view_up_dir_x, view_up_dir_y, view_up_dir_z)

variable.float.view_sun_dir_norm = 1.0 / sqrt((sunPosition.x * sunPosition.x) + (sunPosition.y * sunPosition.y) + (sunPosition.z * sunPosition.z))
variable.float.view_sun_dir_x = sunPosition.x * view_sun_dir_norm
variable.float.view_sun_dir_y = sunPosition.y * view_sun_dir_norm
variable.float.view_sun_dir_z = sunPosition.z * view_sun_dir_norm
uniform.vec3.view_sun_dir = vec3(view_sun_dir_x, view_sun_dir_y, view_sun_dir_z)

variable.float.sun_dir_x = gbufferModelViewInverse.0.0 * view_sun_dir_x + gbufferModelViewInverse.1.0 * view_sun_dir_y + gbufferModelViewInverse.2.0 * view_sun_dir_z
variable.float.sun_dir_y = gbufferModelViewInverse.0.1 * view_sun_dir_x + gbufferModelViewInverse.1.1 * view_sun_dir_y + gbufferModelViewInverse.2.1 * view_sun_dir_z
variable.float.sun_dir_z = gbufferModelViewInverse.0.2 * view_sun_dir_x + gbufferModelViewInverse.1.2 * view_sun_dir_y + gbufferModelViewInverse.2.2 * view_sun_dir_z
uniform.vec3.sun_dir = vec3(sun_dir_x, sun_dir_y, sun_dir_z)

variable.float.view_moon_dir_norm = 1.0 / sqrt((moonPosition.x * moonPosition.x) + (moonPosition.y * moonPosition.y) + (moonPosition.z * moonPosition.z))
variable.float.view_moon_dir_x = moonPosition.x * view_moon_dir_norm
variable.float.view_moon_dir_y = moonPosition.y * view_moon_dir_norm
variable.float.view_moon_dir_z = moonPosition.z * view_moon_dir_norm
uniform.vec3.view_moon_dir = vec3(view_moon_dir_x, view_moon_dir_y, view_moon_dir_z)

variable.float.moon_dir_x = gbufferModelViewInverse.0.0 * view_moon_dir_x + gbufferModelViewInverse.1.0 * view_moon_dir_y + gbufferModelViewInverse.2.0 * view_moon_dir_z
variable.float.moon_dir_y = gbufferModelViewInverse.0.1 * view_moon_dir_x + gbufferModelViewInverse.1.1 * view_moon_dir_y + gbufferModelViewInverse.2.1 * view_moon_dir_z
variable.float.moon_dir_z = gbufferModelViewInverse.0.2 * view_moon_dir_x + gbufferModelViewInverse.1.2 * view_moon_dir_y + gbufferModelViewInverse.2.2 * view_moon_dir_z
uniform.vec3.moon_dir = vec3(moon_dir_x, moon_dir_y, moon_dir_z)

variable.float.view_light_dir_x = if(sunAngle < 0.5, view_sun_dir_x, view_moon_dir_x)
variable.float.view_light_dir_y = if(sunAngle < 0.5, view_sun_dir_y, view_moon_dir_y)
variable.float.view_light_dir_z = if(sunAngle < 0.5, view_sun_dir_z, view_moon_dir_z)
uniform.vec3.view_light_dir = vec3(view_light_dir_x, view_light_dir_y, view_light_dir_z)

variable.float.light_dir_x = if(sunAngle < 0.5, sun_dir_x, moon_dir_x)
variable.float.light_dir_y = if(sunAngle < 0.5, sun_dir_y, moon_dir_y)
variable.float.light_dir_z = if(sunAngle < 0.5, sun_dir_z, moon_dir_z)
uniform.vec3.light_dir = vec3(light_dir_x, light_dir_y, light_dir_z)

# --- PHOTON UNIFORMS FOR WORLD SPACE LIGHT DIR ---

# Custom buffer sizes.
size.buffer.colortex2 = 0.5 0.5
size.buffer.colortex4 = 0.75 0.75
size.buffer.colortex30 = 1.0 0.5

blend.composite75.colortex30 = ONE ONE ZERO ZERO
blend.composite76.colortex30 = ONE ONE ZERO ZERO
blend.composite77.colortex30 = ONE ONE ZERO ZERO
blend.composite78.colortex30 = ONE ONE ZERO ZERO


# -----------------
#     Photonics    
# -----------------

photonics.enabled = false
photonics.lightingMode = basic

#if defined PHOTONICS && defined PHOTONICS_ENABLED && !defined PHOTONICS_RESTIR_COMBINED_GI
image.radiosity_indirect_image = radiosity_indirect rgba rgba16f float true true 1. 1.
#endif

# image.transmittance_lut = transmittance_lut rgba rgba16f float true true 1. 1.
# image.multiscattering_lut = transmittance_lut rgba rgba16f float true true 1. 1.
# image.skyview_lut = transmittance_lut rgba rgba16f float true true 1. 1.

image.transmittance_lut = transmittance_lut RGBA RGBA16F HALF_FLOAT false false 256 64
image.multiscattering_lut = multiscattering_lut RGBA RGBA16F HALF_FLOAT false false 32 32
image.skyview_lut = skyview_lut RGBA RGBA16F HALF_FLOAT false false 200 200

# ---------------------
#     Feature flags    
# ---------------------

iris.features.required = COMPUTE_SHADERS CUSTOM_IMAGES
