#include "/lib/settings.glsl"

// Sky/fog.
const vec3 SKY_COLOR_START = vec3(SKY_COLOR_START_R, SKY_COLOR_START_G, SKY_COLOR_START_B);
const vec3 SKY_COLOR_END = vec3(SKY_COLOR_END_R, SKY_COLOR_END_G, SKY_COLOR_END_B);
const vec3 FOG_COLOR = SKY_COLOR_START;
// Lighting.
const vec3 BLOCKLIGHT_COLOR = vec3(BLOCKLIGHT_COLOR_R, BLOCKLIGHT_COLOR_G, BLOCKLIGHT_COLOR_B);
const vec3 SKYLIGHT_COLOR = vec3(SKYLIGHT_COLOR_R, SKYLIGHT_COLOR_G, SKYLIGHT_COLOR_B);
const vec3 SUNLIGHT_COLOR = vec3(SUNLIGHT_COLOR_INTENSITY);
const vec3 AMBIENT_COLOR = vec3(AMBIENT_COLOR_INTENSITY);
